[env:rp2040]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^6.21.0

build_flags =
    -DUSE_TINYUSB=0
    -DPICO_FLASH_SIZE_BYTES=2097152
